# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: mse-mongo

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build .\Mongo\ --tag ${{ secrets.DOCKER_USERNAME }}/mongo_mse --label "runnumber=${GITHUB_RUN_ID}"
      - name: Tag docker image 
        run: docker tag {{ secrets.DOCKER_USERNAME }}/mongo_mse {{ secrets.DOCKER_USERNAME }}/mongo_mse:1.0
      - name: Push image to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push  {{ secrets.DOCKER_USERNAME }}/mongo_mse:1.0
      - name: Run mongo
        run: docker run -d --name mongo p 27017:27017  {{ secrets.DOCKER_USERNAME }}mongo_mse:1.0 
