# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: mse-mongo

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    steps:
       - name: Get IP Addresses
         id: ip
         uses: candidob/get-runner-ip@v1.0.0

       - name: See IP Addresses
         shell: pwsh
         run: |
           Write-Host ${{ steps.ip.outputs.ipv4 }}
           Write-Host ${{ steps.ip.outputs.ipv6 }}
       - name: create dns mapping
         shell: pwsh
         run: Add-Content -Path "C:\Windows\System32\drivers\etc\hosts" -Value "127.10.0.1 mongo"
       - name: view host mappings
         shell: pwsh
         run: Get-Content -Path "C:\Windows\System32\drivers\etc\hosts"
       - name: Build test application
         run: dotnet build  "${{ github.workspace }}\${{ inputs.PROJECT_NAME }}" 
       #- name: Start mongo
       #  id: start-mongo
       #  shell: pwsh
       #  run: |
       #    docker run --rm -d -p 127.10.0.1:27017:27017 --name mongo  -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=basic mongo:8 "mongod" "--bind_ip_all"
       #- name: check mongo status
       #  id: check_mongo_status
       #  shell: pwsh
       #  run: |
       #    do
       #    {
       #       Start-Sleep -Seconds 2
       #       docker inspect mongo -f '{{.State.Running}}'
       #       $count++
       #    } while ($count -lt 10)

       #- name: Initialize MongoDB Replica Set
       #  run: |
       #    sleep 5 # Give mongo a chance to start up
       #    docker run --rm mongo:6.0 mongosh --host 172.17.0.1 --eval 'rs.initiate({_id: "Workflow", members: [{_id: 0, host: "172.17.0.1:27017"}]})'
       - name: Stop MongoDB
         run: |
           docker rm -f mongo
    
