
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: mse-mongo

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
         
      - name: create dns mapping
        shell: bash
        run: |
          sudo -- sh -c -e "echo '127.10.0.1 mongo' >> /etc/hosts";
      - name: view host mappings
        shell: bash
        run: cat /etc/hosts
      - name: Debug
        shell: bash
        run: |
          echo "hello"
          echo ${{ github.workspace }}
      - name: Start mongo
        id: start-mongo
        shell: bash
        run: |
          docker build ./Mongo/Dockerfile -t mse_mongo
          docker run --rm -d -p 127.10.0.1:27017:27017 --name mongo  -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=basic mse_mongo "mongod" "--bind_ip_all" "--replSet" "Workflow" "--keyFile" "/data/keyfile"

      - name: check mongo container status
        shell: bash
        run: |
          docker inspect mongo
          
          
      #- name: Create Replica Set
      #  shell: bash
      #  run: docker exec -d mongo bash -c "mongosh -u admin -p basic --quiet --eval 'rs.initiate({})' > mongo.out"
      #- name: Check replica created
      #  shell: bash
      #  run: |
      #    docker exec -d mongo "ls -al /data/keyfile"
      #    docker exec -d mongo "cat /data/keyfile"
      - name: test lookup 
        shell: bash
        run: sudo nslookup mongo 
      - name: Build test application
        run: dotnet build  "${{ github.workspace }}/ConsoleApp3.sln" 
      - name: Run test application
        shell: bash 
        run: cd ${{ github.workspace }}/ConsoleApp3/bin/Debug/net8.0 && dotnet ./ConsoleApp3.dll
       #- name: Find solution
       #  shell: pwsh
       #  run: Get-ChildItem -Path ${{ github.workspace }}\ConsoleApp3\bin\Debug\net8.0 -Recurse 
      

   
   #    - name: check mongo status
   #      id: check_mongo_status
   #      shell: pwsh
   #      run: |
   #        do
   #        {
   #           Start-Sleep -Seconds 2
   #           docker inspect mongo -f '{{.State.Running}}'
   #           $count++
   #        } while ($count -lt 10)
   #    - name: Install Mongo Shell into Docker container 
   #      shell: pwsh
   #      run: docker exec -d mongo powershell -c Invoke-WebRequest -Uri https://downloads.mongodb.com/compass/mongosh-2.5.0-win32-x64.zip -OutFile C:\mongo\bin
       #- name: Initialize MongoDB Replica Set
       #  run: |
       #    sleep 5 # Give mongo a chance to start up
       #    docker run --rm mongo:6.0 mongosh --host 172.17.0.1 --eval 'rs.initiate({_id: "Workflow", members: [{_id: 0, host: "172.17.0.1:27017"}]})'
  #     - name: Stop MongoDB
  #       run: |
  #         docker rm -f mongo
    
